version: '3.8'
volumes:
  pgdata:
services:
  python: &python
    build:
        context: .
        dockerfile: docker/python/Dockerfile
    environment:
      - POSTGRES_USER=FastUser
      - POSTGRES_DB=FastDb
      - POSTGRES_PASSWORD=xyBRCSBVcDRncc3R
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    depends_on:
        - postgres
    ports:
        - 80:80
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
  postgres:
    image: postgres:12.4
    environment:
        POSTGRES_USER: FastUser
        POSTGRES_DB: FastDb
        POSTGRES_PASSWORD: xyBRCSBVcDRncc3R
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
        - 5432:5432
